name: Deploy Streamlit App

# Controls when the workflow will run
on:
  push:
    branches:
      - main  # Runs only when code is pushed to the "main" branch

# A job to deploy the app
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Python environment and install dependencies
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 3: Set up AWS credentials using GitHub Secrets
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Accessing the secret securely
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Accessing the secret securely
        aws-region: eu-west-1

    # Step 4: Verify AWS credentials
    - name: Verify AWS credentials
      run: aws sts get-caller-identity
    
    # Step 5: Print environment variables to debug AWS credentials
    - name: Print environment variables
      run: printenv
    
      # Step 6: Run your Streamlit app
    - name: Run Streamlit App
      run: |
        streamlit run streamlit_app.py
