name: Deploy Streamlit App

# Controls when the workflow will run
on:
  push:
    branches:
      - main  # Runs only when code is pushed to the "main" branch

# A job to deploy the app
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment and install dependencies
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 3: Set up AWS credentials from GitHub Secrets
    - name: Configure AWS credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        echo "AWS credentials configured."

    # Step 4: Run your Streamlit app
    - name: Run Streamlit App
      run: |
        streamlit run app.py
